name: Build Verify Windows x86

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # 2026 Node.js 24 zorunluluğu için
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup vcpkg (x86)
        run: |
          vcpkg install libsodium:x86-windows-static

      - name: Setup MSVC (x86)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Compile (MSVC x86 EXE)
        shell: cmd
        run: |
          cl.exe /O2 /MT /EHsc verify.cpp /I %VCPKG_INSTALLATION_ROOT%\installed\x86-windows-static\include /link /LIBPATH:%VCPKG_INSTALLATION_ROOT%\installed\x86-windows-static\lib libsodium.lib user32.lib advapi32.lib /OUT:verify_win_x86.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verify-windows-x86
          path: verify_win_x86.exe
