name: Build Verify App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Node.js 24 zorunluluğu için (2026 uyumluluğu)
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libsodium
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev build-essential

      - name: Compile (G++)
        run: |
          g++ verify.cpp -o verify_linux -lsodium

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verify-linux
          path: verify_linux

  build-windows:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          vcpkg install libsodium:x64-windows-static

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile (MSVC C++)
        shell: cmd
        run: |
          cl.exe /O2 /MT /EHsc verify.cpp /I %VCPKG_INSTALLATION_ROOT%\installed\x64-windows-static\include /link /LIBPATH:%VCPKG_INSTALLATION_ROOT%\installed\x64-windows-static\lib libsodium.lib user32.lib advapi32.lib /OUT:verify_win.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verify-windows
          path: verify_win.exe
