name: Build My CrackMe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: EXE Olarak Derle
      # Dosya adın test.cpp olduğu için bu komutu kullanıyoruz
      run: g++ test.cpp -o CrackMe.exe

    - name: Dosyayi Paketle ve Sun
      uses: actions/upload-artifact@v4
      with:
        name: CrackMe-Programi
        path: CrackMe.exe
